# -*- coding: utf-8 -*-
"""Python Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aY3FB7ZqPuwRHkS7Uy08fGAWubnvt_mc
"""

#Python Calculator:

def add(P, Q):    
   return P + Q   
def subtract(P, Q):   
   return P - Q   
def multiply(P, Q):   
   return P * Q   
def divide(P, Q):   
   return P / Q    

print ("Select the option:")    
print ("a. Add")    
print ("b. Subtract")    
print ("c. Multiply")    
print ("d. Divide")    
    
choice = input("Please enter choice (a/ b/ c/ d): ")    
    
num_1 = int (input ("Please enter the first number: "))    
num_2 = int (input ("Please enter the second number: "))    
    
if choice == 'a':    
   print("Addition :")
   print (num_1, " + ", num_2, " = ", add(num_1, num_2))    
    
elif choice == 'b':    
   print("Subtraction :")
   print (num_1, " - ", num_2, " = ", subtract(num_1, num_2))    
    
elif choice == 'c':    
   print("Multiplication :")
   print (num1, " * ", num2, " = ", multiply(num1, num2))    
elif choice == 'd':    
   print("Division :")
   print (num_1, " / ", num_2, " = ", divide(num_1, num_2))    
else:    
   print ("This is an invalid input")

